security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 1652705501424824
    clientSecret: 90d526b27e8d2a8b3a39fb408d0fdfea
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/v2.9/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
google:
  client:
    clientId: 1060370571916-vh9se6qdkv4790igvhhdannak0b653dr.apps.googleusercontent.com
    clientSecret: ZX-9vUMkBWQJdrT0-0u1TMCu
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope:
    - openid
    - email
    - profile    
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo    

logging:
  level:
    org.springframework.security: DEBUG
